### ISSUE TITLE
Error while viewing orders (payed with icepay)

### ISSUE THREAD

**Issue by hazenlinssenvof** [ICEPAYdev/Magento-2#4] opened 2017-02-14 14:34 UTC
Hello,

I now installed the extension and can do some test payments.
And when i view the orders (only the once payed with ICEPay) i receive the following error:
(updated the module this morning form: Master branch)

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: label in /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Select.php on line 73

Exception #0 (Exception): Notice: Undefined index: label in /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Select.php on line 73
#0 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Select.php(73): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/vhosts...', 73, Array)
#1 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Widget/Grid/Column.php(488): Magento\Backend\Block\Widget\Grid\Column\Filter\Select->getHtml()
#2 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/column_set.phtml(42): Magento\Backend\Block\Widget\Grid\Column->getFilterHtml()
#3 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...')
#4 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid\ColumnSet), '/var/www/vhosts...', Array)
#5 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/vhosts...')
#6 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#7 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sales.transacti...')
#9 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales.transacti...')
#10 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales.transacti...')
#11 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales.transacti...', true)
#12 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('sales.transacti...', true)
#13 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid.columnSet')
#14 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...')
#15 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), '/var/www/vhosts...', Array)
#16 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/vhosts...')
#17 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#18 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#19 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sales.transacti...')
#21 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales.transacti...')
#22 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales.transacti...')
#23 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales.transacti...', false)
#24 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Text/ListText.php(26): Magento\Framework\View\Layout\Interceptor->renderElement('sales.transacti...', false)
#25 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Text\ListText->_toHtml()
#26 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Widget/Tabs.php(387): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/view/adminhtml/templates/widget/tabs.phtml(57): Magento\Backend\Block\Widget\Tabs->getTabContent(Object(Magento\Sales\Block\Adminhtml\Order\View\Tab\Transactions))
#28 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...')
#29 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\View\Tabs), '/var/www/vhosts...', Array)
#30 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/vhosts...')
#31 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#32 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#33 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sales_order_tab...')
#35 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales_order_tab...')
#36 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales_order_tab...')
#37 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales_order_tab...', true)
#38 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('sales_order_tab...')
#39 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('left')
#40 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#41 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#42 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('left', true)
#43 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('left')
#44 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('side.col')
#45 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#46 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#47 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('side.col', true)
#48 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('side.col')
#49 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#50 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#51 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#52 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#53 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#54 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#55 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#56 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#57 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#58 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#59 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#60 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#61 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#62 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#63 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#64 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#65 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#66 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#67 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#68 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#69 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#70 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#71 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#72 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#73 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#74 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#75 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#76 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#77 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#78 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#80 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#81 {main}

Hope this is help, if you need anymore info let me know.

**Comment by hazenlinssenvof** [comment] 2017-02-14 14:58
Oke, cleared files in VAR and switched to production.
Now the error is gone!

**Comment by incandessence** [comment] 2017-02-14 15:08
Hi, I'm very glad the problem is solved; in that case, I'm closing this issue. If you have any questions please let us know, we'd like to help if there's any kind of issue.

**Closed by incandessence** 2017-02-14 15:08 UTC
